export const LEAD_DOMAIN_ERROR_CODES = {
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  LEAD_ARCHIVED: 'LEAD_ARCHIVED',
  LEAD_NOT_ARCHIVED: 'LEAD_NOT_ARCHIVED',
  LEAD_ALREADY_CONVERTED: 'LEAD_ALREADY_CONVERTED',
  COMPANY_REQUIRED: 'COMPANY_REQUIRED',
  INVALID_LEAD_SCORE: 'INVALID_LEAD_SCORE',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_PRIORITY: 'INVALID_PRIORITY',
  INVALID_SOURCE: 'INVALID_SOURCE',
  INVALID_EXPECTED_DEAL_SIZE: 'INVALID_EXPECTED_DEAL_SIZE',
  STATUS_CHANGE_REQUIRES_DEDICATED_ENDPOINT: 'STATUS_CHANGE_REQUIRES_DEDICATED_ENDPOINT',
  WORKSPACE_OWNERSHIP_MISMATCH: 'WORKSPACE_OWNERSHIP_MISMATCH',
  TENANT_SCOPE_MISMATCH: 'TENANT_SCOPE_MISMATCH',
} as const;

export type LeadDomainErrorCode =
  (typeof LEAD_DOMAIN_ERROR_CODES)[keyof typeof LEAD_DOMAIN_ERROR_CODES];

export class LeadDomainError extends Error {
  readonly code: LeadDomainErrorCode;

  constructor(code: LeadDomainErrorCode, message: string) {
    super(message);
    this.name = 'LeadDomainError';
    this.code = code;
  }
}
