export const INTEGRATION_DOMAIN_ERROR_CODES = {
  CONNECTION_NOT_FOUND: 'INTEGRATION_CONNECTION_NOT_FOUND',
  CONNECTION_ARCHIVED: 'INTEGRATION_CONNECTION_ARCHIVED',
  PROVIDER_NOT_FOUND: 'INTEGRATION_PROVIDER_NOT_FOUND',
  DISPLAY_NAME_REQUIRED: 'INTEGRATION_DISPLAY_NAME_REQUIRED',
  CREDENTIALS_REQUIRED: 'INTEGRATION_CREDENTIALS_REQUIRED',
  CONNECTION_NOT_CONNECTED: 'INTEGRATION_CONNECTION_NOT_CONNECTED',
  CONNECTION_DISABLED: 'INTEGRATION_CONNECTION_DISABLED',
  WEBHOOK_NOT_FOUND: 'INTEGRATION_WEBHOOK_NOT_FOUND',
  WEBHOOK_ARCHIVED: 'INTEGRATION_WEBHOOK_ARCHIVED',
  WEBHOOK_NAME_REQUIRED: 'INTEGRATION_WEBHOOK_NAME_REQUIRED',
  WEBHOOK_ENDPOINT_PATH_REQUIRED: 'INTEGRATION_WEBHOOK_ENDPOINT_PATH_REQUIRED',
  WEBHOOK_TARGET_URL_REQUIRED: 'INTEGRATION_WEBHOOK_TARGET_URL_REQUIRED',
  WEBHOOK_SIGNATURE_INVALID: 'INTEGRATION_WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_SIGNATURE_REQUIRED: 'INTEGRATION_WEBHOOK_SIGNATURE_REQUIRED',
  SYNC_JOB_NOT_FOUND: 'INTEGRATION_SYNC_JOB_NOT_FOUND',
  INVALID_PROVIDER: 'INTEGRATION_INVALID_PROVIDER',
  INVALID_DIRECTION: 'INTEGRATION_INVALID_DIRECTION',
  INVALID_STATUS: 'INTEGRATION_INVALID_STATUS',
} as const;

export type IntegrationDomainErrorCode =
  (typeof INTEGRATION_DOMAIN_ERROR_CODES)[keyof typeof INTEGRATION_DOMAIN_ERROR_CODES];

export class IntegrationDomainError extends Error {
  readonly code: IntegrationDomainErrorCode;

  constructor(code: IntegrationDomainErrorCode, message: string) {
    super(message);
    this.name = 'IntegrationDomainError';
    this.code = code;
  }
}
