export const DEAL_DOMAIN_ERROR_CODES = {
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  DEAL_ARCHIVED: 'DEAL_ARCHIVED',
  DEAL_NOT_ARCHIVED: 'DEAL_NOT_ARCHIVED',
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  INVALID_VALUE: 'INVALID_VALUE',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_CLIENT_MISMATCH: 'CONTACT_CLIENT_MISMATCH',
  INVALID_STAGE: 'INVALID_STAGE',
  INVALID_STAGE_TRANSITION: 'INVALID_STAGE_TRANSITION',
  INVALID_PROBABILITY: 'INVALID_PROBABILITY',
  INVALID_PRIORITY: 'INVALID_PRIORITY',
  ALREADY_CONVERTED: 'ALREADY_CONVERTED',
  PROJECT_REQUIRED: 'PROJECT_REQUIRED',
  DEAL_NOT_WON: 'DEAL_NOT_WON',
  WORKSPACE_OWNERSHIP_MISMATCH: 'WORKSPACE_OWNERSHIP_MISMATCH',
} as const;

export type DealDomainErrorCode =
  (typeof DEAL_DOMAIN_ERROR_CODES)[keyof typeof DEAL_DOMAIN_ERROR_CODES];

export class DealDomainError extends Error {
  readonly code: DealDomainErrorCode;

  constructor(code: DealDomainErrorCode, message: string) {
    super(message);
    this.name = 'DealDomainError';
    this.code = code;
  }
}
