import { HttpStatus } from '@nestjs/common';
import { CLIENT_CONTACT_DOMAIN_ERROR_CODES } from '../../modules/clients/domain/client-contact-domain.errors';
import { CLIENT_DOMAIN_ERROR_CODES } from '../../modules/clients/domain/client-domain.errors';
import { PROJECT_DOMAIN_ERROR_CODES } from '../../modules/projects/domain/project-domain.errors';
import { PROJECT_MEMBER_DOMAIN_ERROR_CODES } from '../../modules/projects/domain/project-member-domain.errors';
import { PROJECT_MILESTONE_DOMAIN_ERROR_CODES } from '../../modules/projects/domain/project-milestone-domain.errors';
import { TASK_DOMAIN_ERROR_CODES } from '../../modules/tasks/domain/task-domain.errors';
import { COMMENT_DOMAIN_ERROR_CODES } from '../../modules/comments/domain/comment-domain.errors';
import { FILE_DOMAIN_ERROR_CODES } from '../../modules/files/domain/file-domain.errors';
import { DEAL_DOMAIN_ERROR_CODES } from '../../modules/sales/deals/domain/deal-domain.errors';
import { LEAD_DOMAIN_ERROR_CODES } from '../../modules/sales/leads/domain/lead-domain.errors';

/** Explicit HTTP status mapping for known Client module domain error codes. */
const CLIENT_DOMAIN_ERROR_HTTP_STATUS: Readonly<Partial<Record<string, HttpStatus>>> = {
  [CLIENT_DOMAIN_ERROR_CODES.DISPLAY_NAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.DISPLAY_NAME_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [CLIENT_DOMAIN_ERROR_CODES.SLUG_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [CLIENT_DOMAIN_ERROR_CODES.CLIENT_CODE_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_STATUS]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_STATUS_TRANSITION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_WEBSITE]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_EMAIL]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_COUNTRY_CODE]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_GSTIN]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_PAN]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.INVALID_CURRENCY]: HttpStatus.BAD_REQUEST,
  [CLIENT_DOMAIN_ERROR_CODES.OWNER_NOT_WORKSPACE_MEMBER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.WORKSPACE_OWNERSHIP_MISMATCH]: HttpStatus.FORBIDDEN,
  [CLIENT_DOMAIN_ERROR_CODES.CLIENT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [CLIENT_DOMAIN_ERROR_CODES.CLIENT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.CLIENT_NOT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.RETENTION_WINDOW_EXPIRED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.ARCHIVE_BLOCKED_ACTIVE_PROJECTS]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.ARCHIVE_BLOCKED_OPEN_INVOICES]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.ARCHIVE_BLOCKED_RUNNING_CAMPAIGNS]: HttpStatus.UNPROCESSABLE_ENTITY,
  [CLIENT_DOMAIN_ERROR_CODES.TENANT_SCOPE_MISMATCH]: HttpStatus.FORBIDDEN,
  [CLIENT_CONTACT_DOMAIN_ERROR_CODES.FIRST_NAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [CLIENT_CONTACT_DOMAIN_ERROR_CODES.CLIENT_CONTACT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [CLIENT_CONTACT_DOMAIN_ERROR_CODES.PRIMARY_CONTACT_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_NAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_CODE_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_OWNER_REQUIRED]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_OWNER_NOT_WORKSPACE_MEMBER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [PROJECT_DOMAIN_ERROR_CODES.INVALID_DATE_RANGE]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.INVALID_BUDGET_AMOUNT]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.INVALID_ACTUAL_HOURS]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.CLIENT_REQUIRED]: HttpStatus.BAD_REQUEST,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [PROJECT_DOMAIN_ERROR_CODES.PROJECT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.PROJECT_MEMBER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.USER_NOT_WORKSPACE_MEMBER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.MEMBER_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.MANAGER_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.LAST_MANAGER_REQUIRED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.PROJECT_OWNER_CANNOT_BE_REMOVED]:
    HttpStatus.UNPROCESSABLE_ENTITY,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.INVALID_ROLE]: HttpStatus.BAD_REQUEST,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.INVALID_ALLOCATION]: HttpStatus.BAD_REQUEST,
  [PROJECT_MEMBER_DOMAIN_ERROR_CODES.USER_ID_REQUIRED]: HttpStatus.BAD_REQUEST,
  [PROJECT_MILESTONE_DOMAIN_ERROR_CODES.PROJECT_MILESTONE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [PROJECT_MILESTONE_DOMAIN_ERROR_CODES.NAME_REQUIRED]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.TASK_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.PARENT_TASK_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.SUBTASK_PARENT_MISMATCH]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.TASK_TITLE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.TASK_CODE_NOT_UNIQUE]: HttpStatus.CONFLICT,
  [TASK_DOMAIN_ERROR_CODES.MILESTONE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.ASSIGNEE_NOT_WORKSPACE_MEMBER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.REPORTER_NOT_WORKSPACE_MEMBER]: HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.INVALID_ESTIMATED_HOURS]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.INVALID_PRIORITY]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.INVALID_TYPE]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.MILESTONE_PROJECT_MISMATCH]: HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.OPEN_SUBTASKS_BLOCK_COMPLETION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.INCOMPLETE_DEPENDENCY_BLOCKS_COMPLETION]:
    HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.DEPENDENCY_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [TASK_DOMAIN_ERROR_CODES.DEPENDENCY_CYCLE_DETECTED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [TASK_DOMAIN_ERROR_CODES.DEPENDENCY_SELF_NOT_ALLOWED]: HttpStatus.BAD_REQUEST,
  [TASK_DOMAIN_ERROR_CODES.DEPENDENCY_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.DEPENDENCY_TARGET_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [TASK_DOMAIN_ERROR_CODES.TASK_NOT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [COMMENT_DOMAIN_ERROR_CODES.COMMENT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [COMMENT_DOMAIN_ERROR_CODES.COMMENT_MESSAGE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [COMMENT_DOMAIN_ERROR_CODES.COMMENT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [COMMENT_DOMAIN_ERROR_CODES.THREAD_REPLIES_NOT_SUPPORTED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [FILE_DOMAIN_ERROR_CODES.FILE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [FILE_DOMAIN_ERROR_CODES.FILE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [FILE_DOMAIN_ERROR_CODES.FILE_TOO_LARGE]: HttpStatus.BAD_REQUEST,
  [FILE_DOMAIN_ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: HttpStatus.BAD_REQUEST,
  [DEAL_DOMAIN_ERROR_CODES.DEAL_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [DEAL_DOMAIN_ERROR_CODES.DEAL_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [DEAL_DOMAIN_ERROR_CODES.DEAL_NOT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [DEAL_DOMAIN_ERROR_CODES.TITLE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [DEAL_DOMAIN_ERROR_CODES.INVALID_VALUE]: HttpStatus.BAD_REQUEST,
  [DEAL_DOMAIN_ERROR_CODES.CONTACT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [DEAL_DOMAIN_ERROR_CODES.CONTACT_CLIENT_MISMATCH]: HttpStatus.UNPROCESSABLE_ENTITY,
  [DEAL_DOMAIN_ERROR_CODES.INVALID_STAGE]: HttpStatus.BAD_REQUEST,
  [DEAL_DOMAIN_ERROR_CODES.INVALID_STAGE_TRANSITION]: HttpStatus.UNPROCESSABLE_ENTITY,
  [DEAL_DOMAIN_ERROR_CODES.INVALID_PROBABILITY]: HttpStatus.BAD_REQUEST,
  [DEAL_DOMAIN_ERROR_CODES.ALREADY_CONVERTED]: HttpStatus.CONFLICT,
  [DEAL_DOMAIN_ERROR_CODES.PROJECT_REQUIRED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [DEAL_DOMAIN_ERROR_CODES.DEAL_NOT_WON]: HttpStatus.UNPROCESSABLE_ENTITY,
  [LEAD_DOMAIN_ERROR_CODES.LEAD_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [LEAD_DOMAIN_ERROR_CODES.LEAD_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [LEAD_DOMAIN_ERROR_CODES.LEAD_NOT_ARCHIVED]: HttpStatus.UNPROCESSABLE_ENTITY,
  [LEAD_DOMAIN_ERROR_CODES.LEAD_ALREADY_CONVERTED]: HttpStatus.CONFLICT,
  [LEAD_DOMAIN_ERROR_CODES.COMPANY_REQUIRED]: HttpStatus.BAD_REQUEST,
  [LEAD_DOMAIN_ERROR_CODES.INVALID_LEAD_SCORE]: HttpStatus.BAD_REQUEST,
  [LEAD_DOMAIN_ERROR_CODES.INVALID_SOURCE]: HttpStatus.BAD_REQUEST,
  [LEAD_DOMAIN_ERROR_CODES.INVALID_EXPECTED_DEAL_SIZE]: HttpStatus.BAD_REQUEST,
  [LEAD_DOMAIN_ERROR_CODES.STATUS_CHANGE_REQUIRES_DEDICATED_ENDPOINT]:
    HttpStatus.UNPROCESSABLE_ENTITY,
};

/** Resolves HTTP status for any module domain error code. */
export function mapDomainErrorToHttpStatus(code: string): HttpStatus {
  const explicit = CLIENT_DOMAIN_ERROR_HTTP_STATUS[code];
  if (explicit !== undefined) {
    return explicit;
  }

  if (code.endsWith('_NOT_FOUND')) {
    return HttpStatus.NOT_FOUND;
  }

  if (code.endsWith('_NOT_UNIQUE')) {
    return HttpStatus.CONFLICT;
  }

  if (code.endsWith('_REQUIRED')) {
    return HttpStatus.BAD_REQUEST;
  }

  if (code.startsWith('INVALID_')) {
    return HttpStatus.BAD_REQUEST;
  }

  if (code.endsWith('_MISMATCH')) {
    return HttpStatus.FORBIDDEN;
  }

  if (code.includes('_BLOCKED_')) {
    return HttpStatus.UNPROCESSABLE_ENTITY;
  }

  return HttpStatus.UNPROCESSABLE_ENTITY;
}

/** Maps a domain error code to a stable API error code string. */
export function mapDomainErrorCode(code: string): string {
  return code;
}
