export const CREDIT_NOTE_DOMAIN_ERROR_CODES = {
  CREDIT_NOTE_NOT_FOUND: 'CREDIT_NOTE_NOT_FOUND',
  CREDIT_NOTE_ARCHIVED: 'CREDIT_NOTE_ARCHIVED',
  CLIENT_REQUIRED: 'CREDIT_NOTE_CLIENT_REQUIRED',
  NUMBER_REQUIRED: 'CREDIT_NOTE_NUMBER_REQUIRED',
  INVALID_AMOUNT: 'CREDIT_NOTE_INVALID_AMOUNT',
  INVALID_STATUS: 'CREDIT_NOTE_INVALID_STATUS',
  NOT_APPLICABLE: 'CREDIT_NOTE_NOT_APPLICABLE',
  ALREADY_VOIDED: 'CREDIT_NOTE_ALREADY_VOIDED',
  APPLY_AMOUNT_EXCEEDS: 'CREDIT_NOTE_APPLY_AMOUNT_EXCEEDS',
  WORKSPACE_OWNERSHIP_MISMATCH: 'CREDIT_NOTE_WORKSPACE_OWNERSHIP_MISMATCH',
} as const;

export type CreditNoteDomainErrorCode =
  (typeof CREDIT_NOTE_DOMAIN_ERROR_CODES)[keyof typeof CREDIT_NOTE_DOMAIN_ERROR_CODES];

export class CreditNoteDomainError extends Error {
  readonly code: CreditNoteDomainErrorCode;

  constructor(code: CreditNoteDomainErrorCode, message: string) {
    super(message);
    this.name = 'CreditNoteDomainError';
    this.code = code;
  }
}
