export const CLIENT_DOMAIN_ERROR_CODES = {
  DISPLAY_NAME_REQUIRED: 'DISPLAY_NAME_REQUIRED',
  DISPLAY_NAME_NOT_UNIQUE: 'DISPLAY_NAME_NOT_UNIQUE',
  SLUG_NOT_UNIQUE: 'SLUG_NOT_UNIQUE',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_WEBSITE: 'INVALID_WEBSITE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_COUNTRY_CODE: 'INVALID_COUNTRY_CODE',
  OWNER_NOT_WORKSPACE_MEMBER: 'OWNER_NOT_WORKSPACE_MEMBER',
  WORKSPACE_OWNERSHIP_MISMATCH: 'WORKSPACE_OWNERSHIP_MISMATCH',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_ARCHIVED: 'CLIENT_ARCHIVED',
  CLIENT_NOT_ARCHIVED: 'CLIENT_NOT_ARCHIVED',
  RETENTION_WINDOW_EXPIRED: 'RETENTION_WINDOW_EXPIRED',
  ARCHIVE_BLOCKED_ACTIVE_PROJECTS: 'ARCHIVE_BLOCKED_ACTIVE_PROJECTS',
  ARCHIVE_BLOCKED_OPEN_INVOICES: 'ARCHIVE_BLOCKED_OPEN_INVOICES',
  ARCHIVE_BLOCKED_RUNNING_CAMPAIGNS: 'ARCHIVE_BLOCKED_RUNNING_CAMPAIGNS',
  TENANT_SCOPE_MISMATCH: 'TENANT_SCOPE_MISMATCH',
} as const;

export type ClientDomainErrorCode =
  (typeof CLIENT_DOMAIN_ERROR_CODES)[keyof typeof CLIENT_DOMAIN_ERROR_CODES];

export class ClientDomainError extends Error {
  readonly code: ClientDomainErrorCode;

  constructor(code: ClientDomainErrorCode, message: string) {
    super(message);
    this.name = 'ClientDomainError';
    this.code = code;
  }
}
