export const TASK_DOMAIN_ERROR_CODES = {
  PARENT_TASK_NOT_FOUND: 'PARENT_TASK_NOT_FOUND',
  NESTED_SUBTASKS_NOT_ALLOWED: 'NESTED_SUBTASKS_NOT_ALLOWED',
  SUBTASK_PARENT_MISMATCH: 'SUBTASK_PARENT_MISMATCH',
  TASK_TITLE_REQUIRED: 'TASK_TITLE_REQUIRED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ARCHIVED: 'TASK_ARCHIVED',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_PRIORITY: 'INVALID_PRIORITY',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_ESTIMATED_HOURS: 'INVALID_ESTIMATED_HOURS',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  MILESTONE_NOT_FOUND: 'MILESTONE_NOT_FOUND',
  MILESTONE_PROJECT_MISMATCH: 'MILESTONE_PROJECT_MISMATCH',
  ASSIGNEE_NOT_WORKSPACE_MEMBER: 'ASSIGNEE_NOT_WORKSPACE_MEMBER',
  WORKSPACE_OWNERSHIP_MISMATCH: 'WORKSPACE_OWNERSHIP_MISMATCH',
  TENANT_SCOPE_MISMATCH: 'TENANT_SCOPE_MISMATCH',
} as const;

export type TaskDomainErrorCode =
  (typeof TASK_DOMAIN_ERROR_CODES)[keyof typeof TASK_DOMAIN_ERROR_CODES];

export class TaskDomainError extends Error {
  readonly code: TaskDomainErrorCode;

  constructor(code: TaskDomainErrorCode, message: string) {
    super(message);
    this.name = 'TaskDomainError';
    this.code = code;
  }
}
