export const PURCHASE_BILL_DOMAIN_ERROR_CODES = {
  BILL_NOT_FOUND: 'PURCHASE_BILL_NOT_FOUND',
  BILL_ARCHIVED: 'PURCHASE_BILL_ARCHIVED',
  VENDOR_REQUIRED: 'PURCHASE_BILL_VENDOR_REQUIRED',
  BILL_NUMBER_REQUIRED: 'PURCHASE_BILL_NUMBER_REQUIRED',
  INVALID_STATUS: 'PURCHASE_BILL_INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'PURCHASE_BILL_INVALID_STATUS_TRANSITION',
  INVALID_CURRENCY: 'PURCHASE_BILL_INVALID_CURRENCY',
  INVALID_DATE_RANGE: 'PURCHASE_BILL_INVALID_DATE_RANGE',
  LINE_ITEM_NOT_FOUND: 'PURCHASE_BILL_LINE_ITEM_NOT_FOUND',
  LINE_ITEM_NAME_REQUIRED: 'PURCHASE_BILL_LINE_ITEM_NAME_REQUIRED',
  INVALID_LINE_AMOUNT: 'PURCHASE_BILL_INVALID_LINE_AMOUNT',
  PAYMENT_NOT_FOUND: 'PURCHASE_PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_VOIDED: 'PURCHASE_PAYMENT_ALREADY_VOIDED',
  INVALID_PAYMENT_AMOUNT: 'PURCHASE_PAYMENT_INVALID_AMOUNT',
  PAYMENT_EXCEEDS_BALANCE: 'PURCHASE_PAYMENT_EXCEEDS_BALANCE',
  BILL_NOT_PAYABLE: 'PURCHASE_BILL_NOT_PAYABLE',
  WORKSPACE_OWNERSHIP_MISMATCH: 'PURCHASE_BILL_WORKSPACE_OWNERSHIP_MISMATCH',
} as const;

export type PurchaseBillDomainErrorCode =
  (typeof PURCHASE_BILL_DOMAIN_ERROR_CODES)[keyof typeof PURCHASE_BILL_DOMAIN_ERROR_CODES];

export class PurchaseBillDomainError extends Error {
  readonly code: PurchaseBillDomainErrorCode;

  constructor(code: PurchaseBillDomainErrorCode, message: string) {
    super(message);
    this.name = 'PurchaseBillDomainError';
    this.code = code;
  }
}
